name: rubyci-screenshot

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 14 * * *' # Daily at 14:30 UTC


jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          ruby-version: 2.7

      - name: Setup the environment
        run: |
          sudo snap install chromium
          bundle install

      - name: Run the script
        run: bundle exec ruby rubyci-screenshot.rb
        env:
          RUBYCI_SCREENSHOT_SLACK_API_TOKEN: ${{ secrets.RUBYCI_SCREENSHOT_SLACK_API_TOKEN }}
          RUBYCI_SCREENSHOT_SLACK_CHANNEL_ID: ${{ secrets.RUBYCI_SCREENSHOT_SLACK_CHANNEL_ID }}

#      - uses: actions/upload-artifact@master
#        with:
#          name: rubyci-screenshot
#          path: rubyci.png
